shim/interfaces.go

The golang protos were moved from fabric/protos to fabric-protos-go and
the chaincode golang shim to fabric-chaincode-go, so the relative
protos/common/common.proto references no longer make any sense.  This
simply replaces those relative references with links to the godoc.
Signed-off-by: Jason Yellick <jyellick@us.ibm.com>

FAB-16723 Fix a few stale references to protos

---

go.mod
go.sum
shim/chaincodeserver.go
shim/handler.go
shim/handler_test.go
shim/internal/config.go
shim/internal/config_test.go
shim/internal/mock/client_stream.go
shim/internal/server.go
shim/internal/server_test.go
shim/shim.go
shim/shim_test.go

Chaincode-as-server shim implementation for go chaincodes
* Creates chaincode server using the "Chaincode" proto service
* exposes ChaincodeServer api for running chaincodes
* hooks it up with post-connection stream processing (adjusts shim.go to handle either flow)
* For TLS, follows Peer's implementation for most part
`NOTE: latest fabric master was built and unit-tested by replacing vendored code with these changes.`

Chaincode server shim side#fab 14086

---

go.mod
go.sum
shim/stub_test.go

During all the shuffling of the protos and chaincode shim, we picked up a dependency on `gogo/protobuf` instead of `golang/protobuf`. This fixes the dependency.

Remove inadvertent usage of gogo/protobuf

---

shim/internal/config.go
shim/internal/config_test.go

Client CAs were not set but client certificate verification was expected
by the chaincode server.
FABCG-11
Signed-off-by: muralisr <srinivasan.muralidharan99@gmail.com>

TLS Client auth not working for chaincode server

---

pkg/cid/README.md
pkg/cid/cid.go
pkg/cid/cid_test.go

Added HasOUValue func to ClientIdentity that checks if an OU with a specified value is present in the client's X509 cert.
This way granular access control in the chaincode can also be done based on OU values instead of only on attributes from the custom extra extension in the cert that is not supported by external CA services.
Link to JIRA item FABCG-12: https://jira.hyperledger.org/browse/FABCG-12

HasOUValue function for cid library

---

shim/internal/config.go
shim/internal/config_test.go

This change removes ClientCAs from the TLS config and, as such, breaks chaincode as client flows. We discovered this when bumping our chaincode dependency caused most of the integration tests to fail.
Since this repo now hosts an active module, we are reverting this to prevent users from encountering further issues.
Reverts hyperledger/fabric-chaincode-go#15

Revert "TLS Client auth not working for chaincode server"

---

shim/internal/config.go
shim/internal/config_test.go

The previous fix block chaincode-as-client scenarios. This fix correctly
sets Client CAs for the server scenario without breaking client.
Fabric integration tests (via `make integration-test`) locally with this
change to ensure vendoring this change is safe.
FABCG-11
Signed-off-by: muralisr <srinivasan.muralidharan99@gmail.com>

Redo TLS Config for chaincode-as-server

---

pkg/cid/README.md

The import seems to be incorrect since the `pkg` directory is not a sub-directory of `shim` (anymore?).

Fixed import in the README.md file

---

shim/stub.go
shim/stub_test.go

[FABCG-13](https://jira.hyperledger.org/browse/FABCG-13)

[FABCG-13] Support new API for retrieving MSPID via the CORE_PEER_LOCALMSPID env var

---

CODEOWNERS

Be a bit more consistent with hyperledger/fabric and hyperledger/fabric-protos

Use fabric-core-maintainers group in CODEOWNERS

---

shim/interfaces.go

Indicate that only a single chaincode event can be used.
Signed-off-by: David Enyeart <enyeart@us.ibm.com>

Clarify SetEvent comment

---

shim/interfaces.go

Clarify that GetHistoryForKey() sorts results from latest to oldest,
as mentioned in the v2.0.0 release notes.
Signed-off-by: David Enyeart <enyeart@us.ibm.com>

Clarify GetHistoryForKey results ordering

---

.github/workflows/build.yml
ci/tools/tools.go
shim/internal/config_test.go
shim/stub.go

Add gh-actions workflow
Update the one formatting, two lint and failing tests assertion that prevents the build from completing
The assertion (assert.Equal) fixes should be a temporary solution as I believe we need to change the assertion library.
To the one used by the main fabric repo - as that seems to be able to cope with equality of TLSConfig structures.   The current one here doesn't cope with objects with functions.
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>

Add GHA support

---

shim/interfaces.go
shimtest/mockstub.go

Required to complete #44
Signed-off-by: James Taylor <jamest@uk.ibm.com>

Add PurgePrivateData to ChaincodeStubInterface

---

shim/interfaces.go
shim/stub.go

Updated documentation for getStateByPartialCompositeKey, getStateByPartialCompositeKeyWithPagination and getPrivateDataByPartialCompositeKey.
Specified that we can't do a full key query: https://jira.hyperledger.org/browse/FABCN-376

 Updated documentation for getStateByPartialCompositeKey

---

go.mod
v2/go.mod

Update go.mod files to use toolchain compatible full version.

Change go.mod to 1.21.0

---

.golangci.yml

New versions of gosec implemented stricter type conversion. Since the integer values will be small in the conversions in this codebase, it is safe to suppress these gosec warnings.

Suppress false positive in gosec

---

pkg/statebased/statebasedimpl_test.go
shim/chaincodeserver.go
shim/handler.go
shim/handler_test.go
shim/interfaces.go
shim/internal/config.go
shim/internal/server.go
shim/shim.go
shim/shim_test.go
shim/stub.go
shim/stub_test.go

https://github.com/hyperledger/fabric/issues/5086

add write batch

---

shim/handler.go
shim/interfaces.go
shim/stub.go
shim/stub_test.go

https://github.com/hyperledger/fabric/issues/5086

remove ResetWriteBatch

---

shim/interfaces.go

Document that the batch methods have no effect if the peer does not support write batching, and that no error is returned.

Clarify godoc for write batching

---

shim/batch.go
shim/handler.go
shim/handler_test.go
shim/stub.go
shim/stub_test.go

Avoid holding transaction-specific state in the handler, which must then be protected by multiple locks. This is error prone and is a potential performance bottleneck. Instead, extract batch writes to a separate struct for clarity, and maintain the batch write state in the stub, which is unique to a specific transaction so requires no locking.
The stub (and associated batch write state) is also discarded after a transaction invocation so there is no risk of memory leaks due to redundant batch write state being left in the shared handler.

Refactor write batching

---

shim/stub_test.go

https://github.com/hyperledger/fabric/issues/5086

add unit tests for WriteBatch

---

shim/handler.go
shim/interfaces.go
shim/stub.go
shim/stub_test.go

https://github.com/hyperledger/fabric/issues/5116

add support GetMultipleKeys

---

pkg/cid/cid.go

There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.

refactor: use slices.Contains to simplify code
